# Generated by Django 4.1.3 on 2022-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=66),
        ),
    ]
