# Generated by Django 4.1.3 on 2022-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_uploadimage_alter_film_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
